services:
  redis:
    image: bitnami/redis:7.2
    container_name: redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis-official.conf:/usr/local/etc/redis/redis.conf
      - ./tmp:/opt/redis/tmp/
    environment:
    - REDIS_PASSWORD=passw0rd
